os:
- linux
language: dart
sudo: true
addons:
  apt:
    packages:
    - libstdc++6
before_script:
- git clone https://github.com/flutter/flutter.git -b beta
- ./flutter/bin/flutter doctor
script:
- cd app
- ./flutter/bin/flutter test
cache:
  directories:
  - flutter
  - $HOME/.pub-cache
