os:
- linux
language: dart
sudo: true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-noto
git:
  depth: 3
env:
- FLUTTER_VERSION=stable
- FLUTTER_VERSION=beta
matrix:
  allow_failures:
  - env: FLUTTER_VERSION=beta
install:
- echo 'Avoid default Travis CI install step'
before_script:
- git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
- ./flutter/bin/flutter doctor
script:
- ./flutter/bin/flutter test
cache:
  directories:
  - flutter
  - $HOME/.pub-cache
